"use client";
import { useState, type FormEvent } from "react";
import { ProtectedPage } from "@/components/layout/protected-page";
import { createCompatibility, downloadReport } from "@/lib/api/astrology";
import type { BirthDetails, Compatibility } from "@/types/astrology";

function details(data: FormData, prefix: string): BirthDetails { return { name: String(data.get(`${prefix}_name`)), gender: String(data.get(`${prefix}_gender`)), date_of_birth: String(data.get(`${prefix}_date`)), time_of_birth: String(data.get(`${prefix}_time`)), place: String(data.get(`${prefix}_place`)) }; }
function PersonFields({ prefix, title }: { prefix: string; title: string }) { return <fieldset><legend>{title}</legend><label>Name<input name={`${prefix}_name`} required /></label><label>Gender / identity<input name={`${prefix}_gender`} placeholder="Optional" /></label><label>Date of birth<input name={`${prefix}_date`} type="date" required /></label><label>Time of birth<input name={`${prefix}_time`} type="time" required /></label><label>Place of birth<input name={`${prefix}_place`} placeholder="Kanpur, India" required /></label></fieldset>; }

export default function CompatibilityPage() { const [result, setResult] = useState<Compatibility | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(""); const data = new FormData(e.currentTarget); try { setResult((await createCompatibility(details(data, "a"), details(data, "b"))).data); } catch (err) { setError(err instanceof Error ? err.message : "Unable to calculate compatibility."); } finally { setLoading(false); } } return <ProtectedPage title="Love Compatibility">{result ? <CompatibilityReport result={result} /> : <form className="flow-card compatibility-form" onSubmit={submit}><p>Compare two profiles without making assumptions about relationship type or gender.</p><div className="people-grid"><PersonFields prefix="a" title="Person A"/><PersonFields prefix="b" title="Person B"/></div>{error && <p className="flow-error">{error}</p>}<button className="primary-action" disabled={loading}>{loading ? "Calculating..." : "Calculate compatibility"}</button></form>}</ProtectedPage>; }

function CompatibilityReport({ result }: { result: Compatibility }) { return <div className="report-stack"><section className="flow-card compatibility-hero"><div className="score-ring"><strong>{result.overall_score}</strong><span>of {result.maximum_score}</span></div><div><span>VedAstro match report</span><h2>{result.person_a.name} &amp; {result.person_b.name}</h2><p>{result.summary}</p></div><button className="primary-action" onClick={() => downloadReport(result.report_id)}>Download PDF</button></section>{result.components.length > 0 && <section className="factor-grid">{result.components.map((factor, index) => <article className="stat-tile" key={`${factor.name}-${index}`}><span>{factor.name}</span><strong>{factor.nature}</strong>{factor.description && <p>{factor.description}</p>}{factor.score != null && factor.maximum != null && <div className="score-bar"><i style={{width: `${Math.min(100, factor.score / factor.maximum * 100)}%`}} /></div>}</article>)}</section>}<div className="two-column"><section className="flow-card"><h2>Strengths</h2><ul>{result.strengths.map(x => <li key={x}>{x}</li>)}</ul></section><section className="flow-card"><h2>Areas to understand</h2><ul>{result.areas_to_understand.map(x => <li key={x}>{x}</li>)}</ul></section></div><section className="flow-card"><h2>Guidance</h2><p>{result.guidance}</p></section></div>; }
